name: Vysteria-RankedSpawners
version: ${project.version}
main: dev.xcodiq.vysteriarankedspawners.RankedSpawners
authors: [xCodiq, Vysteria]
depend: [Vysteria-Library, Vault]
softdepend: [PlaceholderAPI]
description: Vysteria Ranked Spawners with custom shop and rankup system
website: www.vysteria.com
